FROM python:3.12-slim AS base

# prepare container
RUN apt-get update -y && apt upgrade -y && apt-get clean -y
RUN apt-get install ffmpeg -y
RUN apt-get install unzip -y
RUN apt-get install curl -y

# Install Poetry
RUN pip install poetry